Add explicit typing to TH structuralEquality.
Without the change to structuralEquality, the new tests would result in errors
like the following:

test/Test/TH.hs:51:11: error:
    • Couldn't match type ‘a1’ with ‘(:~:) @{k0} a0 a0’
      Expected: Maybe a1
        Actual: Maybe ((:~:) @{k0} a0 a0)
    • ‘a1’ is untouchable
        inside the constraints: "int" ~ "int"
        bound by a pattern with constructor: T3_Int :: Int -> T3 "int",
                 in a case alternative
        at test/Test/TH.hs:51:11-41
    • In the expression: Just Refl
      In the expression:
        if (x1_ab5y == y1_ab5z) then Just Refl else Nothing
      In a case alternative:
          T3_Int y1_ab5z
            -> if (x1_ab5y == y1_ab5z) then Just Refl else Nothing
   |
51 |   (==) = $(structuralEquality [t|T3|] [])
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^