CI: Stop testing GHC 8.4
Unfortunately, it's quite hard to test GHC 8.4 with a Nix Flake–based setup.
Attempting to do so with NixOS 20.03, a version of NixOS that includes GHC
8.4.4, results in the following error:

```
error: flake 'github:nixos/nixpkgs/5272327b81ed355bbed5659b8d303cf2979b6953' has an unsupported attribute 'edition', at /nix/store/1q41mjncrlsds9nxwr2xrl6lb9g48man-source/flake.nix:4:3
```

This means that this version of NixOS is likely too old. Since newer versions
of NixOS don't include GHC 8.4.4, let's just make things easier and not include
GHC 8.4 in CI.